function raw = caliendo_parro_2015()
%USTARIFF.ELASTICITY.SOURCES.CALIENDO_PARRO_2015  Caliendo & Parro (2015, ReStud) elasticities.
%
%   raw = ustariff.elasticity.sources.caliendo_parro_2015()
%
%   Returns a struct with:
%     .epsilon  - 20x1 vector of trade elasticities (ISIC Rev 3, 2-digit)
%     .sectors  - 20x1 cell array of sector labels
%     .isic3    - 20x1 cell array of ISIC Rev 3 codes
%
%   Source: Caliendo & Parro (2015) "Estimates of the Trade and Welfare
%   Effects of NAFTA", Review of Economic Studies.
%   Table 1, 99% sample column (benchmark estimates).
%
%   Parameter: theta_j (Frechet dispersion, positive). epsilon = theta.
%   Classification: isic_rev3 (20 tradable sectors)

    raw.epsilon = [ ...
         9.11;  ... % 1  Agriculture
        13.53;  ... % 2  Mining
         2.62;  ... % 3  Food
         8.10;  ... % 4  Textiles
        11.50;  ... % 5  Wood
        16.52;  ... % 6  Paper
        64.85;  ... % 7  Petroleum
         3.13;  ... % 8  Chemicals
         1.67;  ... % 9  Plastics
         2.41;  ... % 10 Minerals
         3.28;  ... % 11 Basic metals
         6.99;  ... % 12 Metal products
         1.45;  ... % 13 Machinery n.e.c.
        12.95;  ... % 14 Office
        12.91;  ... % 15 Electrical
         3.95;  ... % 16 Communication
         8.71;  ... % 17 Medical
         1.84;  ... % 18 Auto
         0.39;  ... % 19 Other transport
         3.98]; ... % 20 Other manufacturing

    raw.sectors = { ...
        'Agriculture'; ...
        'Mining'; ...
        'Food'; ...
        'Textiles'; ...
        'Wood'; ...
        'Paper'; ...
        'Petroleum'; ...
        'Chemicals'; ...
        'Plastics'; ...
        'Minerals'; ...
        'Basic metals'; ...
        'Metal products'; ...
        'Machinery n.e.c.'; ...
        'Office'; ...
        'Electrical'; ...
        'Communication'; ...
        'Medical'; ...
        'Auto'; ...
        'Other transport'; ...
        'Other manufacturing'};

    raw.isic3 = { ...
        '01-05'; '10-14'; '15-16'; '17-19'; '20'; '21-22'; '23'; ...
        '24'; '25'; '26'; '27'; '28'; '29'; '30'; '31'; '32'; ...
        '33'; '34'; '35'; '36-37'};
end
