function raw = fontagne_2022()
%USTARIFF.ELASTICITY.SOURCES.FONTAGNE_2022  Fontagne, Guimbard & Orefice (2022, JIE) elasticities.
%
%   raw = ustariff.elasticity.sources.fontagne_2022()
%
%   Returns a struct with:
%     .epsilon  - 19x1 vector of trade elasticities (TiVA sector level)
%     .sectors  - 19x1 cell array of sector labels
%     .tiva     - 19x1 cell array of TiVA codes
%
%   Source: Fontagne, Guimbard & Orefice (2022) "Tariff-based Product-Level
%   Trade Elasticities", Journal of International Economics.
%   Table 8 (p. 18), TiVA 2016 sector-level elasticities.
%
%   Parameter: epsilon (negative trade elasticity). Our epsilon = |epsilon_paper|.
%   Classification: tiva_19 (19 sectors with significant estimates)

    raw.epsilon = [ ...
         2.91;  ... % 1  Agriculture, hunting, forestry, fishing
         3.41;  ... % 2  Mining and quarrying
         4.17;  ... % 3  Food products, beverages, tobacco
         4.71;  ... % 4  Textiles, leather, footwear
         8.80;  ... % 5  Wood and products of wood/cork
         8.21;  ... % 6  Pulp, paper, printing, publishing
         3.67;  ... % 7  Coke, refined petroleum, nuclear fuel
        10.56;  ... % 8  Chemicals and chemical products
         6.75;  ... % 9  Rubber and plastics products
         4.79;  ... % 10 Other non-metallic mineral products
         7.39;  ... % 11 Basic metals
         4.22;  ... % 12 Fabricated metal products
         5.01;  ... % 13 Machinery and equipment n.e.c.
         5.14;  ... % 14 Computer, electronic, optical equipment
         4.11;  ... % 15 Electrical machinery and apparatus
         8.92;  ... % 16 Motor vehicles, trailers, semi-trailers
         8.99;  ... % 17 Other transport equipment
         4.06;  ... % 18 Manufacturing n.e.c.; recycling
         8.35]; ... % 19 Other community, social, personal services

    raw.sectors = { ...
        'Agriculture, hunting, forestry, fishing'; ...
        'Mining and quarrying'; ...
        'Food products, beverages, tobacco'; ...
        'Textiles, leather, footwear'; ...
        'Wood and products of wood/cork'; ...
        'Pulp, paper, printing, publishing'; ...
        'Coke, refined petroleum, nuclear fuel'; ...
        'Chemicals and chemical products'; ...
        'Rubber and plastics products'; ...
        'Other non-metallic mineral products'; ...
        'Basic metals'; ...
        'Fabricated metal products'; ...
        'Machinery and equipment n.e.c.'; ...
        'Computer, electronic, optical equipment'; ...
        'Electrical machinery and apparatus'; ...
        'Motor vehicles, trailers, semi-trailers'; ...
        'Other transport equipment'; ...
        'Manufacturing n.e.c.; recycling'; ...
        'Other community, social, personal services'};

    raw.tiva = { ...
        'C01T05'; 'C10T14'; 'C15T16'; 'C17T19'; 'C20'; 'C21T22'; ...
        'C23'; 'C24'; 'C25'; 'C26'; 'C27'; 'C28'; 'C29'; 'C30T33X'; ...
        'C31'; 'C34'; 'C35'; 'C36T37'; 'C90T93'};
end
