function raw = giri_yi_yilmazkuday_2021()
%USTARIFF.ELASTICITY.SOURCES.GIRI_YI_YILMAZKUDAY_2021  GYY (2021, JIE) elasticities.
%
%   raw = ustariff.elasticity.sources.giri_yi_yilmazkuday_2021()
%
%   Returns a struct with:
%     .epsilon  - 19x1 vector of trade elasticities (ISIC Rev 2, 3-digit)
%     .sectors  - 19x1 cell array of sector labels
%     .isic2    - 19x1 cell array of ISIC Rev 2 codes
%
%   Source: Giri, Yi & Yilmazkuday (2021) "Gains from Trade: Does Sectoral
%   Heterogeneity Matter?", Journal of International Economics.
%   Table 2, SMM-PPML column (benchmark estimates).
%
%   Parameter: theta_s (Frechet dispersion, positive). epsilon = theta.
%   Classification: isic_rev2 (19 tradable manufacturing sectors)
%
%   NOTE: Covers manufacturing only. Agriculture, mining, petroleum,
%   electronics, and machinery are NOT covered. Missing WIOD sectors
%   use fallback epsilon = 4 (Simonovska-Waugh uniform).

    raw.epsilon = [ ...
        3.57;  ... % 1  Food products
        3.57;  ... % 2  Beverages and Tobacco
        3.27;  ... % 3  Textiles
        4.41;  ... % 4  Wearing apparel
        5.28;  ... % 5  Leather products
        4.77;  ... % 6  Footwear
        4.17;  ... % 7  Wood products
        4.47;  ... % 8  Furniture
        2.97;  ... % 9  Paper and printing
        3.75;  ... % 10 Other chemicals
        4.38;  ... % 11 Rubber products
        3.87;  ... % 12 Plastic products
        5.94;  ... % 13 Pottery
        5.61;  ... % 14 Glass products
        3.87;  ... % 15 Other non-metallic minerals
        8.94;  ... % 16 Iron and steel
        5.07;  ... % 17 Fabricated metal products
        3.27;  ... % 18 Machinery, electric
        4.47]; ... % 19 Transport equipment

    raw.sectors = { ...
        'Food products'; ...
        'Beverages and Tobacco'; ...
        'Textiles'; ...
        'Wearing apparel'; ...
        'Leather products'; ...
        'Footwear'; ...
        'Wood products'; ...
        'Furniture'; ...
        'Paper and printing'; ...
        'Other chemicals'; ...
        'Rubber products'; ...
        'Plastic products'; ...
        'Pottery'; ...
        'Glass products'; ...
        'Other non-metallic minerals'; ...
        'Iron and steel'; ...
        'Fabricated metal products'; ...
        'Machinery, electric'; ...
        'Transport equipment'};

    raw.isic2 = { ...
        '311'; '313-314'; '321'; '322'; '323'; '324'; '331'; '332'; ...
        '341-342'; '352'; '355'; '356'; '361'; '362'; '369'; '371'; ...
        '381'; '383'; '384'};
end
