function raw = lashkaripour_2021()
%USTARIFF.ELASTICITY.SOURCES.LASHKARIPOUR_2021  Lashkaripour (2021, JIE) elasticities.
%
%   raw = ustariff.elasticity.sources.lashkaripour_2021()
%
%   Returns a struct with:
%     .epsilon  - 16x1 vector of trade elasticities (WIOD 16-sector aggregation)
%     .sectors  - 16x1 cell array of sector labels
%
%   Source: Lashkaripour (2021) "Cost of a Global Tariff War"
%   Table values from Lashkaripour (2021, JIE).
%
%   Classification: wiod_16 (15 goods + 1 services)

    % Epsilon values from Lashkaripour (2021, JIE)
    % Sectors 1-15: goods (agriculture, mining, manufacturing)
    % Sector 16: services (aggregate)
    raw.epsilon = [ ...
         0.67;  ... % 1  Agriculture, forestry, fishing
        13.53;  ... % 2  Mining and quarrying
         0.47;  ... % 3  Food, beverages, tobacco
         3.33;  ... % 4  Textiles, apparel, leather
         5.73;  ... % 5  Wood, paper, printing
         8.50;  ... % 6  Coke and refined petroleum
        14.94;  ... % 7  Chemicals, pharmaceuticals
         0.91;  ... % 8  Rubber, plastics, non-metallic minerals
         1.69;  ... % 9  Basic metals
         1.47;  ... % 10 Fabricated metals
         3.28;  ... % 11 Computer, electronic, optical
         3.44;  ... % 12 Electrical equipment
         3.63;  ... % 13 Machinery and equipment
         1.38;  ... % 14 Transport equipment
         1.64;  ... % 15 Other manufacturing; repair
         5.00]; ... % 16 Services (aggregate)

    raw.sectors = { ...
        'Agriculture, forestry, fishing'; ...
        'Mining and quarrying'; ...
        'Food products, beverages, tobacco'; ...
        'Textiles, wearing apparel, leather'; ...
        'Wood, paper, printing'; ...
        'Coke and refined petroleum'; ...
        'Chemicals and pharmaceuticals'; ...
        'Rubber, plastics, non-metallic minerals'; ...
        'Basic metals'; ...
        'Fabricated metals'; ...
        'Computer, electronic, optical'; ...
        'Electrical equipment'; ...
        'Machinery and equipment n.e.c.'; ...
        'Transport equipment'; ...
        'Other manufacturing; repair'; ...
        'Services (aggregate)'};
end
