function raw = lashkaripour_lugovskyy_2023()
%USTARIFF.ELASTICITY.SOURCES.LASHKARIPOUR_LUGOVSKYY_2023  LL (2023, AER) elasticities.
%
%   raw = ustariff.elasticity.sources.lashkaripour_lugovskyy_2023()
%
%   Returns a struct with:
%     .epsilon  - 14x1 vector of trade elasticities (ISIC Rev 4, 14 industries)
%     .sectors  - 14x1 cell array of sector labels
%     .mu       - 14x1 vector of scale elasticities (for reference)
%
%   Source: Lashkaripour & Lugovskyy (2023) "Profits, Scale Economies, and
%   the Gains from Trade and Industrial Policy", American Economic Review.
%   Table 3 (p. 2792), sigma_k - 1 column.
%
%   Parameter: sigma_k (CES). Reported as (sigma_k - 1). epsilon = sigma_k - 1.
%   Classification: isic4_14 (14 traded industries)

    raw.epsilon = [ ...
        6.227;  ... % 1  Agriculture and Mining
        2.303;  ... % 2  Food
        3.359;  ... % 3  Textiles, Leather, Footwear
        3.896;  ... % 4  Wood
        2.646;  ... % 5  Paper
        0.636;  ... % 6  Petroleum
        3.966;  ... % 7  Chemicals
        5.157;  ... % 8  Rubber and Plastic
        5.283;  ... % 9  Minerals
        3.004;  ... % 10 Basic and Fabricated Metals
        7.750;  ... % 11 Machinery
        1.235;  ... % 12 Electrical and Optical Equipment
        2.805;  ... % 13 Transport Equipment
        6.169]; ... % 14 N.E.C. and Recycling

    raw.sectors = { ...
        'Agriculture and Mining'; ...
        'Food'; ...
        'Textiles, Leather, Footwear'; ...
        'Wood'; ...
        'Paper'; ...
        'Petroleum'; ...
        'Chemicals'; ...
        'Rubber and Plastic'; ...
        'Minerals'; ...
        'Basic and Fabricated Metals'; ...
        'Machinery'; ...
        'Electrical and Optical Equipment'; ...
        'Transport Equipment'; ...
        'N.E.C. and Recycling'};

    raw.mu = [ ...
        0.143;  0.393;  0.224;  0.229;  0.320;  1.220;  0.232; ...
        0.140;  0.167;  0.209;  0.120;  0.552;  0.129;  0.152];
end
