function raw = shapiro_2016()
%USTARIFF.ELASTICITY.SOURCES.SHAPIRO_2016  Shapiro (2016) elasticities.
%
%   raw = ustariff.elasticity.sources.shapiro_2016()
%
%   Returns a struct with:
%     .epsilon  - 13x1 vector of trade elasticities
%     .sectors  - 13x1 cell array of sector labels
%
%   Source: Shapiro (2016) "Trade Costs, CO2, and the Environment"
%   Table 2, Panel B, Column 4 (IV estimates).
%
%   Parameter: theta (negative trade elasticity). epsilon = |theta|.
%   Classification: shapiro_13 (13 tradable sectors, custom aggregation)

    raw.epsilon = [ ...
         3.34;  ... % 1  Agriculture, forestry
         3.45;  ... % 2  Mining
         5.26;  ... % 3  Food, beverages, tobacco
        18.56;  ... % 4  Textiles
         9.95;  ... % 5  Apparel, leather
         5.90;  ... % 6  Wood
         5.77;  ... % 7  Paper, printing
         8.95;  ... % 8  Petroleum, coal, minerals
         1.55;  ... % 9  Chemicals, rubber, plastics
        12.94;  ... % 10 Metals
        10.84;  ... % 11 Machinery, electrical
         6.87;  ... % 12 Transport equipment
        12.76]; ... % 13 Other

    raw.sectors = { ...
        'Agriculture, forestry'; ...
        'Mining'; ...
        'Food, beverages, tobacco'; ...
        'Textiles'; ...
        'Apparel, leather'; ...
        'Wood'; ...
        'Paper, printing'; ...
        'Petroleum, coal, minerals'; ...
        'Chemicals, rubber, plastics'; ...
        'Metals'; ...
        'Machinery, electrical'; ...
        'Transport equipment'; ...
        'Other'};
end
